### PR TITLE
support budgie panel transparency

### PR DESCRIPTION
**Pull request by danielpinto8zz6**
This adds support for the budgie panel dynamic / full transparency option

### CODE REVIEW

**Comment by hrdwrrsk** [comment]
seems 'out of rule', I need panel transparency that compatible with some wallpapers, not full panel transparency (40% or 50% opacity is good)

or add shadows in text and icons for easier visibility

**Comment by danielpinto8zz6** [comment]
humm okay, I did like the default theme of budgie, since this is a setting you can allways have it default

**Comment by hrdwrrsk** [comment]
merged, but totally untested. I should install Ubuntu 18.04 minimal install + Budgie from ubuntu-budgie/backports ppa to test it soon :\

**Comment by danielpinto8zz6** [comment]
Check it: https://streamable.com/424q3

**Comment by hrdwrrsk** [comment]
known problems:
- with some wallpapers, running app indicator is hard to see

screenshot from 2018-11-30 15-57-02

**Pull request merged**
